### ISSUE TITLE
FS.create is too slow to use as a command line client

### ISSUE THREAD

**Issue by kit-ty-kate** [mirage/ocaml-git#286]
Would it be possible to have a fast version of ```FS.create``` for such uses ?
I guess one way would be to have a ```FS.create_client``` or ```FS.create_server``` instead maybe ? Or something like ```FS.longterm_create``` and ```FS.create``` ? I don't know what would be the best interface here but that's just my two cents.

**Comment by dinosaure** [comment]
So, I will explain more deeply this issue to understand the situation.

In my mind, the current version of `ocaml-git` was focus on the memory allocation. It's a strong constraint about the implementation of the server part and, obviously, the implementation of an unikernel as a `git` server.

So, in this way, extraction of a `git` object (`read`) and store of a `git` object (`write`) was developed with a bound-memory mind at any level of the API (low-level, cf. `Unpack` module - high-level, cf. `Lwt_pool` on `Store` module). Finally, in this situation, the client can do any operation with a predictable consumption of the memory - we avoid a stress about the GC, we allocated at the beginning (so when you use `create`) every buffer (`angstrom`/decoder's buffer, `zlib`'s buffer and window, input/output's buffer and _undelta-ification_'s buffer) needed to extract any `git` objects of your repository.

So we need to explain deeply what is going on specifically about the PACK file to understand this slow computation and the difference (in the design) with `git`.

So, about the PACK file, this big bottleneck is about _delta-ified_ objects.

Of course, if the `git` object requested is a _loose_ file (so, in the `.git/objects` directory) **or** a non _delta-ified_ object, the only process needed is to _inflate_ the file (_loose_) or the area (_packed_) and decode it with `angstrom`.

But if the `git` object is _delta-ified_ (so it is necessary located in the PACK file), it's more complicated to _reconstruct_ it. Indeed, we can imagine a `blob` A, which is _delta-ified_ with a `blob` B. This means than, if you want to have A, you need to reconstruct it with B - so, obviously, we need to load B in your memory. Then, you apply the _patch_ between A and B to reconstruct A. And finally, we can decode (with `angstrom`) A to return the expected OCaml value of the requested `git` object.

So when I talk about _delta-ification_, it's most about that. Load the requested _delta-ified_ object, load the source object, apply the _patch_ and return the result.

And if you follow my explanation, you can understand than for one object requested, we load (in memory and in reality) 2 objects. However, I will put an other stuff in this explanation: the `git` object (source) needed to reconstruct your requested `git` object **can be** _delta-ified_ too.

So now, we will talk about _chain of delta-ification_ which is commonly around 50.

Now we can talk about _design_ (and specifically about the difference with `git` - about performance because this is the purpose of this issue).

So because I developed this part with, as the final goal, the implementation of the server, the value `t` (which represent your repository) will have a long live. So, as a server development mind (and the OCaml GC matrice), it's better to allocate **only one time** needed buffers (`Cstruct.t`) to extract any `git` objects. However, we need to ensure to **don't have** any problem about what is really needed.

So, currently, `ocaml-git` at the beginning will compute all of your PACK files, calculate the maximum of the _chain of delta-ification_ (as I said, around 50 - we efine this number as the variable _n_) and allocate _n_ times `Cstruct.t` which can fill **the biggest object of your repository** (including _loose_ objects). We did this because the worst case is:

> the client request the biggest object of the `git` repository which is _delta-ified_ _n_ times.

So to reconstruct it, we need to load _n_ objects in the memory, _folding_ on the `apply` function (to `apply` patch) and reconstruct step by step needed objects to finally reconstruct the requested object. In this case, we ensure than **any** objects **fit** in any allocated `Cstruct.t` and because we already computed the maximum of the _chain of delta-ification_, we ensure than to reconstruct **any** object, we don't need more than _n_ buffers (`Cstruct.t`).

So the final purpose of the first computation ensure than we really don't need to allocate any intermediate buffers (`Cstruct.t`) to construct **any** `git` objects - and, on a server context, that means we allocate only on the minor heap for any requested objects (`blob` object is a special case however).

Finally, about `git`, why `git` does not do this (and choose to be fast than memory-bounded). It's because `git` **is** a command-line software. So, it terminates in any case, it never run an infinite loop like a server (which wait requests from outside and process it then). When you push to a `git` server, it's exactly the same, you run a shell (with SSH or telnet) which will execute a `git` builtin (so `git-upload-pack`) and terminate on it. So `git` core team never developed `git` as a long-lived program which we need to take care about the memory consumption.

In this case, when you request a `git` object with `git`, it will allocate _n_ buffers needed to reconstruct your object (obviously if your object is _delta-ified_) and because the program will terminate (for sure), all is de-allocated at the end. 

So, now, about `ocaml-git` and specifically about the MirageOS plaform (which does not have a shell ... lol), it's not possible to think in the same mind and it's why (only at the beginning) `ocaml-git` is slow - however, then any `read` and `write` is _relatively_ fast.

So, the conclusion ...

The good new is we can change that. The bad new is: I really don't want to delete this behavior (obviously because it's a security issue). So, as @jpdeplaix said, we can find a way to provide two _politics_ of allocations, one about the server side (calculate all at the beginning) and an other about a command-line where we have a _broadcasts_ allocation politic (like, we just don't care ...).

**Comment by yetanotherion** [comment]
Thanks for this explanation. Reading
> So, currently, ocaml-git at the beginning will compute all of your PACK files, calculate the maximum of the chain of delta-ification (as I said, around 50 - we efine this number as the variable n) and allocate n times Cstruct.t which can fill the biggest object of your repository (including loose objects)

I'm wondering how the **git push** use case is handled.
From my understanding, the server needs to compute and how many _new_ CStruct.t are necessary and allocate them. Is that so?
This should be zero often enough, but I wonder whether someone crafting and pushing an anomalous branch with enough chain of delta-ification could not severely impact the performance of the server?

**Comment by dinosaure** [comment]
About the Git `push`, the way to update the server is to send a PACK file. Behind the hood, we compute a diff between the DAG reachable by the local commit and the DAG reachable by the server commit. Then, you have a set of Git object (commit, blob, etc.) - note than some of these objects could be already available on the server side but we don't care if we resend them.

With this set, we produce an optimized PACK file and send it to the server.

Finally, the server will __just__ check the PACK file, if it can reconstruct the DAG and produce the IDX file associated. The server stores it and it's done!

The big deal about memory consumption is the generation of the PACK file which can be huge. The key in `ocaml-git` is to have a lightweight representation of the PACK file which does not need to have a direct access of Git object to serialize them in the PACK file. We have [only references](https://github.com/mirage/ocaml-git/blob/master/src/git/pack.ml#L653) (hash) to Git object and a [lightweight](https://github.com/mirage/ocaml-git/blob/master/src/git/rabin.ml#L456) representation of the delta-ification when Git objects are under it.

Finally, from this lightweight representation, we start a stream which, sometimes, asks to load Git objects in memory - then the GC will do the work to clean it. So it's like a _call-by-need_ politic which is close to what `git` does.

**Comment by yetanotherion** [comment]
Thanks again. What I still don't get is how this 
**N** = maximum of CStruct.t required to read any object in the repository, is static in the server use case.
I Imagine the server would be something like
```
FS.create ~root:"." () >>= fun t ->
  <loop for requests, do read and writes>
```
If "." is empty in the begining, **N** will be either 0 or 1.
After the first write, from what I understood in your former post, a new PACK file would be required. If 
* N = 0, there may be an issue, and 
* if N=1 the only way not to increment N, may be to put all the content of what is represented by each sha1 in the relevant PACK file isn't it (ending with consuming much more storage than git)?

There most probably is something I'm missing here.

**Comment by dinosaure** [comment]
About the level (the _n_ number), it's an arbitrary number - like the maximum of the depth of the _chain of delta-ification_ is 50. However, your are true and this number can be upper than 50. So it's why we compute the PACK file to determine this number.

Then, if this number is lower or equal to the already computed maximum, we don't change anything. In the other case, we allocate what is needed for the new PACK file. This allocation is hidden to the final user.

You point a problem. Currently, we need to believe than the engine (`Pack_engine`) will do correctly this work (to growth `Cstruct.t` needed) but we can think about a way to let the user to do this operation.

**Comment by dinosaure** [comment]
I just finished the biggest part to allow the user to control allocation about PACK file 👍 you can look and share your advise in the PR.
