### ISSUE TITLE
negotiation trouble for pull from a remote with common ancestors

### ISSUE THREAD

**Issue by hannesm** [mirage/ocaml-git#364]
setup is as follows:
- https://github.com/hannesm/testzone is the repository I cloned (at commit id f08d64523257528980115942481d5ddd13d2c1ba)
- starting a unikernel which does a git clone with no local reference
- I push commit b88599cb4217c175110f6e2a810079d954524814 to master via the shell command `git push` on my laptop
- unikernel does a git pull (provoked by an external trigger, i sent a packet)

the (rather extensive, including after `Net.read` and before `Net.write`) log output from the unikernel is at https://gist.github.com/hannesm/1b5bc41c31c25555557ea7c59edaf872 -- please have a look at line 2106 and below https://gist.github.com/hannesm/1b5bc41c31c25555557ea7c59edaf872#file-tcp-error-txt-L2106-L2109 -- here the `0008 NACK` is consumed by the negotiation engine, but the following `ACK f1ea1cdc9cc3d8816..` stays in the buffer and is only parsed at the end (after all the write `have` happened)...

**Comment by hannesm** [comment]
FWIW, https://github.com/hannesm/ocaml-git/commit/7fc7bb87fad3039afd3444268f4d2a97d933c886 solves this issue for me (tested with ssh, push and pull now). I'm ignoring the `` `Again `` and sending out a `` `Done `` instead.

**Comment by dinosaure** [comment]
Ok I will try to reproduce behaviors and try to understand what we should do (and try to understand what Git does), thanks for this precise report, a regression test will be easy to make then.

**Comment by hannesm** [comment]
gentle ping, this issue has been biting me several times (and I suspect it will affect others using ocaml-git and other git implementation to push + pull the same repository -- rather than a single ocaml-git which is the only one pushing + pulling), any chance to formulate a regression test (based on the information + repositories I linked to above) and a fix out? thanks!

**Comment by dinosaure** [comment]
I did a PoC about this specific bug. It seems much more bigger than what we can believe when it highlight the non-ability for us to rightly do a negotiation with server. Even if it can be fixed fixed with https://github.com/hannesm/ocaml-git/commit/7fc7bb87fad3039afd3444268f4d2a97d933c886, the result is to give no chance to the server to produce the smallest PACK file as it can (with the knowledge of what we have).

The error come from 2 sides:
- Currently, `ocaml-git` wants to send as soon as possible packets to the server - it should not do that when it must _bufferize_ `have` packets where the server side _bufferize_ `ACK` packets - in others words, the association between `have` and `ACK` is a bit asynchronous. 
- The negotiation engine does not do what the server expects. It's hard to extract a simpler synchronization algorithm from the Git code-base so I mostly do a translation as is.

The PoC is available here: https://github.com/dinosaure/not-so-smart.git

**Comment by dinosaure** [comment]
The scenario was integrated into the test suite and it's work for TCP, SSH and HTTP(S).
