### ISSUE TITLE
Writing a module of type Git.S

### ISSUE THREAD

**Issue by njayinthehouse** [mirage/ocaml-git#380]
**Description**
I'm interested in implementing a module for performing git-like operations in Cassandra. Specifically, I'm writing a module that can be passed to functor [`Irmin_git.Content_addressable`](https://mirage.github.io/irmin/irmin-git/Irmin_git/index.html#module-Content_addressable), in order to maintain a content-addressable store on Cassandra.

**Specific questions**
1. What exactly is a [buffer](https://github.com/mirage/ocaml-git/blob/e24f11abd50e21c7636909b7f0fbe8def7daf4e5/src/git/minimal.ml#L29), and how are we using it?
2. What is a PACK stream/What does the [`Pack`](https://github.com/mirage/ocaml-git/blob/e24f11abd50e21c7636909b7f0fbe8def7daf4e5/src/git/minimal.ml#L131) module do?

**Comment by dinosaure** [comment]
Hi!

So if I understand correctly, you want to simulate Git with Cassandra? I'm not really aware about Cassandra but I can give you some details about Git.

> What exactly is a buffer?

Currently, `buffer` is a set of `Cstruct.t` used to make a `Git.t` - this type is abstracted and can be constructed only on a specialized target (eg. [`git` with a file-system](https://github.com/mirage/ocaml-git/blob/master/src/git/store.ml#L1189) or [`git-mem`](https://github.com/mirage/ocaml-git/blob/master/src/git/mem.ml#L87)).

It help to bound allocation needed by common Git algorithms. By this way, `read` or `write` operations will use this set of buffers instead to allocate _in-the-fly_ `Cstruct.t` - and, by this way, try to fix an old issue `Out_of_memory`.

> What is a PACK stream/What does the Pack module do?

In Git, we have 2 ways to store Git objects:
- _loose_ objects
- _pack_-file

The first is used when you make a `git commit`, some loose files appears in your disk. The second appears when you `git clone`/`git fetch`. The PACK stream is the format exchanged between 2 Git entities (like you and GitHub).

An other case is when you do a `git gc` when all of your _loose_ files will be _packed_ into a new PACK file - currently, even if it's possible to make a PACK file, the `git gc` is not yet implemented.

Finally, from a PACK file, we can extract several Git objects (commit, tag, tree or blob). According to what I said, the PACK stream is mostly used by the [`Sync.mli` module](https://github.com/mirage/ocaml-git/blob/master/src/git/sync.mli) to be able to download/upload Git objects.

### About your goal

Required types and functions are quite independent from the Git format where you can consider `type buffer = unit` if you want and a PACK file as a simple format (like a succession of Git objects without compression and _delta-ification_).

However, because `irmin` wants to have a way to synchronize two peers over a _protocol_, you must implement the PACK stream.

**Comment by njayinthehouse** [comment]
Thanks for your detailed response, I have a much better idea of how to go about this.
