### ISSUE TITLE
Converting to and fro between Value.t and Cstruct.t

### ISSUE THREAD

**Issue by njayinthehouse** [mirage/ocaml-git#381]
I'm trying to convert `Value.t` objects into `Cstruct.t` objects (and vice versa) to store them in (load them from) a distributed database. I see many functions that might help me defined in the [`Value.Raw` module](https://github.com/mirage/ocaml-git/blob/e24f11abd50e21c7636909b7f0fbe8def7daf4e5/src/git/value.ml). 

There seems to be a convenient [`of_raw_with_header`](https://github.com/mirage/ocaml-git/blob/e24f11abd50e21c7636909b7f0fbe8def7daf4e5/src/git/value.mli#L151), which looks like exactly what I need. If I'm not mistaken, [`to_raw`](https://github.com/mirage/ocaml-git/blob/e24f11abd50e21c7636909b7f0fbe8def7daf4e5/src/git/value.mli#L132) serializes the value with a header containing information about what kind of Git object the value is. I'm not clear on exactly how this happens, though. (It seems like the documentation beside it is outdated.)

1. What do the named arguments `raw` and `etmp` represent?
2. What exactly does this function return? (I see its return type is not `(Cstruct.t, EncoderRaw.error) result` as I expected.)

**Comment by dinosaure** [comment]
> 1. What do the named arguments raw and etmp represent?

There are internal buffers used to encode/decode the Git objects. They can be re-used like:
```ocaml
let raw = Cstruct.create 0x100
let etmp = Cstruct.create 0x100

let o1 = to_raw ~raw ~etmp my_git_object1
let o2 = to_raw ~raw ~etmp my_git_object2
```

Because the allocation of a `Cstruct.t` costs (in time), we prefer to allocate such buffers only one time and re-use it then as long as we need.

Into #380, you ask me about the `type buffer`. Internally, this type contains such buffers.

> 2. What exactly does this function return? (I see its return type is not (Cstruct.t, EncoderRaw.error) result as I expected.)

It's about design of `Cstruct.t`. Two `Cstruct.t` can share the same memory place. Underlying type of a `Cstruct.t` is a [`Bigarray.Array1.t`](https://caml.inria.fr/pub/docs/manual-ocaml/libref/Bigarray.html). 

To ensure that the returned value is created by function, we prefer to return a `string` instead a `Cstruct.t` - in fact, a `val foo : Cstruct.t -> Cstruct.t` does not imply an allocation and such function can not ensure that the given `Cstruct.t` is physically different to the returned `Cstruct.t`.

At the end, something like `of_raw (Cstruct.of_string (to_raw o))` shows explicitly an allocation of a `Cstruct.t` (with `Cstruct.of_string`) and ensure, by this way, that nothing is shared between `to_raw` and `of_raw`.

**Comment by njayinthehouse** [comment]
Thanks once again. :)
