### ISSUE TITLE
release

### ISSUE THREAD

**Issue by hannesm** [mirage/ocaml-git#392]
it looks to me that https://github.com/mirage/ocaml-git/pull/389 is a pretty important bug fix, would you mind to cut a release (eventually addressing #384 before that?), mainly with that bugfix? thanks a lot.

**Comment by dinosaure** [comment]
So, I'm able to cut a little release with this fix but I'm currently on `ocaml-git` with a large update which should fix:
- #387, #364, #363 (about Smart protocol)
- #375, #357 (about PACK file)
- #344 (about `js_of_ocaml` - see mirage/encore#24)

It's a bit deep where `carton` and `encore` are neuralgic items of the next version of `ocaml-git` (they update the core). I will try to do something at the end of this week, otherwise I will cut a little release.

**Comment by hannesm** [comment]
I'd appreciate a minor release with the bugfix first, and a bigger release with all the other improvements and bugfixes later :) (thus if there's any regression, we can safely go back to the bugfix release). thanks.

**Comment by hannesm** [comment]
> I will try to do something at the end of this week, otherwise I will cut a little release.

any idea when to expect a bugfix release?

**Comment by dinosaure** [comment]
I will cut a little release as soon as I can (need a release of `encore`).

**Comment by hannesm** [comment]
thanks @dinosaure :)

**Comment by dinosaure** [comment]
Fixed by ocaml/opam-repository#16734.
