### ISSUE TITLE
git and irmin: remove hard-wired http dependencies

### ISSUE THREAD

**Issue by hannesm** [mirage/ocaml-git#513]
At the moment, irmin-mirage-git depends on conduit/cohttp/git-paf, so there's no way to configure a irmin+git unikernel which only supports the git-over-tcp (git-over-ssh) protocol. in some use cases, I'd like to avoid the dependency cone of http/ssh/..., and only use the tcp (ssh) transport mechanism.

AFAICT some API changes are necessary to enable such a modularization.

**Comment by hannesm** [comment]
I have this data point (updating a [branch of Canopy](https://github.com/hannesm/Canopy/tree/future-full) from <earlier> (conduit 2.2) to <now>) -- and that unikernel serves only http:

## Packages removed
```
fiat-p256.0.2.3
fieldslib.v0.14.0
git-cohttp-mirage.3.3.3
hacl_x25519.0.2.2
ppx_fields_conv.v0.14.2
```

## New packages installed
```
biniou.1.2.1
ca-certs.0.2.1
ca-certs-nss.3.64.0.1
cohttp-lwt-unix.4.0.0
conduit-lwt-unix.4.0.0
dns-tsig.5.0.1
easy-format.1.3.2
faraday.0.7.2
git-paf.3.4.0
h2.0.8.0
hpack.0.2.0
httpaf.0.7.1
letsencrypt.0.2.5
mirage-crypto-ec.0.10.1
paf.0.0.3
pbkdf.1.1.0
yojson.1.7.0
```

## Packages with version changes
```
awa.0.0.1->0.0.3
awa-mirage.0.0.1->0.0.3
carton.0.4.0->0.4.1
carton-git.0.4.0->0.4.1
carton-lwt.0.4.0->0.4.1
cohttp.2.5.5->4.0.0
cohttp-lwt.2.5.5->4.0.0
cohttp-mirage.2.5.5->4.0.0
conduit-mirage.2.2.1->4.0.0
dns.4.6.3->5.0.1
dns-client.4.6.3->5.0.1
git.3.3.3->3.4.0
git-mirage.3.3.3->3.4.0
irmin.2.5.3->2.6.0
irmin-git.2.5.3->2.6.0
irmin-mirage.2.5.3->2.6.0
irmin-mirage-git.2.5.3->2.6.0
mirage.3.10.1->3.10.4
mirage-crypto.0.8.10->0.10.1
mirage-crypto-pk.0.8.10->0.10.1
mirage-crypto-rng.0.8.10->0.10.1
mirage-crypto-rng-mirage.0.8.10->0.10.1
ppx_irmin.2.5.3->2.6.0
tls.0.12.8->0.13.1
tls-mirage.0.12.8->0.13.1
x509.0.11.2->0.13.0
```

**Comment by dinosaure** [comment]
For some details, the HTTP "transmission protocol" is a bit different than TCP/IP and SSH (because, it is stateless). So, in our implementation, it's special case concretized by a functor needed to get the Smart protocol implementation. In the best world, we should be able to abstract the HTTP "transmission protocol" with `mimic` as we do for TCP/IP and SSH. By this way, as TCP/IP and SSH, we will not strictly depend on a specific implementation nor something related to HTTP.

However, due to the special case of HTTP, I'm not sure that it will be easy to do that.

**Comment by hannesm** [comment]
Another unnecessary dependency chain is that without using `Git_mirage_dns.Make` (which results in a depedency on dns-client) I'm unable to connect to a remote url -- even if I specify an IP address explicitly.

I'd be in favour to reduce the run time dependencies (also, with the above into account, the build time dependencies as well).
